name: example
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
#author: Thomas Hourlier <email@example.com>

environment:
  sdk: '>=1.24.0 <3.0.0'

dependencies:
  angular: ^4.0.0
  angular_components: ^0.6.0
  graphql_client: ^0.0.3
  graphql_client_generator: ^0.0.0

dev_dependencies:
  angular_test: ^1.0.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.0
  build_runner: ^0.4.0

dependency_overrides:
# we won't need this when angular 5 will be released
  code_builder: ^2.0.0-alpha+1
  graphql_client:
    path: ../graphql_client
  graphql_client_generator:
    path: ../graphql_client_generator

transformers:
- angular:
    entry_points:
      - web/main.dart
      - test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter
# graphql_client_generator transformer, should not be used
#- graphql_client_generator:
#    collectionFields:
#      - nodes
#      - edges

web:
  compiler:
    debug: dartdevc