name: graphql_client
description: A GraphQL client.
version: 0.0.4
homepage: https://github.com/dart-graphql/graphql_client
authors:
  - Thomas Hourlier <hourliert@gmail.com>
  - TruongSinh Tran-Nguyen <i@truongsinh.pro>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  http: ^0.11.3
  logging: ^0.11.3
  meta: ^1.1.1

dev_dependencies:
  mockito: ^4.0.0
  test: ^1.5.3
  perfectionist: ^2.0.0
